name: "Deploy to AWS"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted   

    steps:
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: "Checkout code"
        uses: actions/checkout@v2
        
      - name: "Install dependencies"
        run: npm install
       
      - name: "Run the tests"
        run: npm test

      - name: "Deploy to AWS with PM2"
        run: pm2 restart my-app || pm2 start server.js --name my-app --env PORT=3000
